-- -------------------------------------------------------------
-- Agent
-- -------------------------------------------------------------

-- Create user
CREATE USER SFREEMAN IDENTIFIED BY password;
CREATE USER CKLEIN IDENTIFIED BY password;
CREATE USER MCURTIS IDENTIFIED BY password;
CREATE USER JHUNTER IDENTIFIED BY password;
CREATE USER KJACKSON IDENTIFIED BY password;
CREATE USER ECARPENTER IDENTIFIED BY password;
CREATE USER AMYERS IDENTIFIED BY password;

-- Grant create session
GRANT CREATE SESSION TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;

-- Grant read
GRANT READ ON AGENT TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;
GRANT READ ON PLAN TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;
GRANT READ ON CUSTOMER TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;
GRANT READ ON PAYMENT TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;
GRANT READ ON PREMIUM TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;
GRANT READ ON PURCHASE TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;
GRANT READ ON CLAIM TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;


-- -------------------------------------------------------------
-- Customer
-- -------------------------------------------------------------

-- Create user
CREATE USER AARONAUSTIN IDENTIFIED BY password;
CREATE USER CASTILLOMICHAEL IDENTIFIED BY password;
CREATE USER SOSAKAITLYN IDENTIFIED BY password;
CREATE USER COREYSKINNER IDENTIFIED BY password;
CREATE USER KRISTEN73 IDENTIFIED BY password;

-- Grant create session
GRANT CREATE SESSION TO AARONAUSTIN, CASTILLOMICHAEL, SOSAKAITLYN, COREYSKINNER, KRISTEN73;

-- Grant read
GRANT READ ON PLAN TO AARONAUSTIN, CASTILLOMICHAEL, SOSAKAITLYN, COREYSKINNER, KRISTEN73;
GRANT READ ON CUSTOMER TO AARONAUSTIN, CASTILLOMICHAEL, SOSAKAITLYN, COREYSKINNER, KRISTEN73;
GRANT READ ON PAYMENT TO AARONAUSTIN, CASTILLOMICHAEL, SOSAKAITLYN, COREYSKINNER, KRISTEN73;
GRANT READ ON PREMIUM TO AARONAUSTIN, CASTILLOMICHAEL, SOSAKAITLYN, COREYSKINNER, KRISTEN73;
GRANT READ ON PURCHASE TO AARONAUSTIN, CASTILLOMICHAEL, SOSAKAITLYN, COREYSKINNER, KRISTEN73;
GRANT READ ON CLAIM TO AARONAUSTIN, CASTILLOMICHAEL, SOSAKAITLYN, COREYSKINNER, KRISTEN73;
