-- -------------------------------------------------------------
-- Agent
-- -------------------------------------------------------------

-- Create user
CREATE USER SFREEMAN IDENTIFIED BY password;
CREATE USER CKLEIN IDENTIFIED BY password;
CREATE USER MCURTIS IDENTIFIED BY password;
CREATE USER JHUNTER IDENTIFIED BY password;
CREATE USER KJACKSON IDENTIFIED BY password;
CREATE USER ECARPENTER IDENTIFIED BY password;
CREATE USER AMYERS IDENTIFIED BY password;

-- Grant create session
GRANT CREATE SESSION TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;

-- Grant read
GRANT READ ON AGENT TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;
GRANT READ ON PLAN TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;
GRANT READ ON CUSTOMER TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;
GRANT READ ON PAYMENT TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;
GRANT READ ON PREMIUM TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;
GRANT READ ON PURCHASE TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;
GRANT READ ON CLAIM TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;

-- Grant insert
GRANT INSERT ON CUSTOMER TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;
GRANT INSERT ON PREMIUM TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;
GRANT INSERT ON PURCHASE TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;
GRANT INSERT ON CLAIM TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;

-- Grant update
GRANT UPDATE ON AGENT TO SFREEMAN, CKLEIN, MCURTIS, JHUNTER, KJACKSON, ECARPENTER, AMYERS;

-- -------------------------------------------------------------
-- Customer
-- -------------------------------------------------------------

-- Create user
CREATE USER AARONAUSTIN IDENTIFIED BY password;
CREATE USER CASTILLOMICHAEL IDENTIFIED BY password;
CREATE USER SOSAKAITLYN IDENTIFIED BY password;
CREATE USER COREYSKINNER IDENTIFIED BY password;
CREATE USER KRISTEN73 IDENTIFIED BY password;

-- Grant create session
GRANT CREATE SESSION TO AARONAUSTIN, CASTILLOMICHAEL, SOSAKAITLYN, COREYSKINNER, KRISTEN73;

-- Grant read
GRANT READ ON PLAN TO AARONAUSTIN, CASTILLOMICHAEL, SOSAKAITLYN, COREYSKINNER, KRISTEN73;
GRANT READ ON CUSTOMER TO AARONAUSTIN, CASTILLOMICHAEL, SOSAKAITLYN, COREYSKINNER, KRISTEN73;
GRANT READ ON PAYMENT TO AARONAUSTIN, CASTILLOMICHAEL, SOSAKAITLYN, COREYSKINNER, KRISTEN73;
GRANT READ ON PREMIUM TO AARONAUSTIN, CASTILLOMICHAEL, SOSAKAITLYN, COREYSKINNER, KRISTEN73;
GRANT READ ON PURCHASE TO AARONAUSTIN, CASTILLOMICHAEL, SOSAKAITLYN, COREYSKINNER, KRISTEN73;
GRANT READ ON CLAIM TO AARONAUSTIN, CASTILLOMICHAEL, SOSAKAITLYN, COREYSKINNER, KRISTEN73;

-- Grant insert
GRANT INSERT ON PAYMENT TO AARONAUSTIN, CASTILLOMICHAEL, SOSAKAITLYN, COREYSKINNER, KRISTEN73;

-- Grant update
GRANT UPDATE ON CUSTOMER TO AARONAUSTIN, CASTILLOMICHAEL, SOSAKAITLYN, COREYSKINNER, KRISTEN73;
GRANT UPDATE ON PAYMENT TO AARONAUSTIN, CASTILLOMICHAEL, SOSAKAITLYN, COREYSKINNER, KRISTEN73;

-- -------------------------------------------------------------
-- Financer
-- -------------------------------------------------------------

CREATE USER ROGEROLIVER IDENTIFIED BY password;
CREATE USER TNGUYEN IDENTIFIED BY password;
CREATE USER JOSHUATHOMPSON IDENTIFIED BY password;
CREATE USER BRENDA96 IDENTIFIED BY password;
CREATE USER UKOCH IDENTIFIED BY password;

-- Grant create session
GRANT CREATE SESSION TO ROGEROLIVER, TNGUYEN, JOSHUATHOMPSON, BRENDA96, UKOCH;

-- Grant read
GRANT READ ON PLAN TO ROGEROLIVER, TNGUYEN, JOSHUATHOMPSON, BRENDA96, UKOCH;
GRANT READ ON FINANCER TO ROGEROLIVER, TNGUYEN, JOSHUATHOMPSON, BRENDA96, UKOCH;
GRANT READ ON CLAIM TO ROGEROLIVER, TNGUYEN, JOSHUATHOMPSON, BRENDA96, UKOCH;

-- Grant update
GRANT UPDATE ON FINANCER TO ROGEROLIVER, TNGUYEN, JOSHUATHOMPSON, BRENDA96, UKOCH;
GRANT UPDATE ON CLAIM TO ROGEROLIVER, TNGUYEN, JOSHUATHOMPSON, BRENDA96, UKOCH;

-- -------------------------------------------------------------
-- Planner
-- -------------------------------------------------------------

CREATE USER STACEYGONZALEZ IDENTIFIED BY password;
CREATE USER SAUNDERSROGER IDENTIFIED BY password;
CREATE USER MONTOYAMARTIN IDENTIFIED BY password;
CREATE USER WEBERJOSEPH IDENTIFIED BY password;
CREATE USER KATHRYNFOX IDENTIFIED BY password;

-- Grant create session
GRANT CREATE SESSION TO STACEYGONZALEZ, SAUNDERSROGER, MONTOYAMARTIN, WEBERJOSEPH, KATHRYNFOX;

GRANT READ ON PLANNER TO STACEYGONZALEZ, SAUNDERSROGER, MONTOYAMARTIN, WEBERJOSEPH, KATHRYNFOX;
GRANT READ ON PLAN TO STACEYGONZALEZ, SAUNDERSROGER, MONTOYAMARTIN, WEBERJOSEPH, KATHRYNFOX;

-- Grant insert
GRANT INSERT ON PLAN TO STACEYGONZALEZ, SAUNDERSROGER, MONTOYAMARTIN, WEBERJOSEPH, KATHRYNFOX;

-- Grant update
GRANT UPDATE ON PLANNER TO STACEYGONZALEZ, SAUNDERSROGER, MONTOYAMARTIN, WEBERJOSEPH, KATHRYNFOX;
GRANT UPDATE ON PLAN TO STACEYGONZALEZ, SAUNDERSROGER, MONTOYAMARTIN, WEBERJOSEPH, KATHRYNFOX;