-- Create application context
CREATE OR REPLACE CONTEXT FINANCER_CTX USING FINANCER_CTX_PKG;

-- Create a PL/SQL package to set the application context
CREATE OR REPLACE PACKAGE FINANCER_CTX_PKG IS
    PROCEDURE SET_FINANCERID;
END;
/

CREATE OR REPLACE PACKAGE BODY FINANCER_CTX_PKG IS
    PROCEDURE SET_FINANCERID AS
        FINANCERID NUMBER;
    BEGIN
        SELECT
            FINANCER_ID INTO FINANCERID
        FROM
            SYSTEM.FINANCER
        WHERE
            USERNAME = SYS_CONTEXT('USERENV',
            'SESSION_USER');
        DBMS_SESSION.SET_CONTEXT('financer_ctx', 'financer_id', FINANCERID);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            NULL;
    END SET_FINANCERID;
END;
/

-- Create a logon trigger to run the application context PL/SQL package
CREATE TRIGGER SET_FINANCERID_CTX_TRIG AFTER LOGON ON DATABASE
BEGIN
    FINANCER_CTX_PKG.SET_FINANCERID;
END;
/

-- Used to delete the context trigger (use only when needed)
DROP TRIGGER SET_FINANCERID_CTX_TRIG;
