DELETE FROM SYSTEM.CUSTOMER WHERE CUSTOMER_ID = '7';
UPDATE (SELECT PAYMENT_METHOD_ID, CUSTOMER_ID FROM SYSTEM.CUSTOMER WHERE CUSTOMER_ID='1') SET PAYMENT_METHOD_ID = '1';

DELETE FROM SYSTEM.CLAIM WHERE CLAIM_ID = '8';

DELETE FROM SYSTEM.PURCHASE WHERE PURCHASE_ID = '6';

DELETE FROM SYSTEM.PREMIUM WHERE PREMIUM_ID = '7';

DELETE FROM SYSTEM.PAYMENT WHERE PAYMENT_ID = '11';

DELETE FROM SYSTEM.PLAN WHERE PLAN_ID = '6';


SELECT * FROM SYSTEM.CUSTOMER;
SELECT * FROM SYSTEM.CLAIM;
SELECT * FROM SYSTEM.PURCHASE;
SELECT * FROM SYSTEM.PREMIUM;
SELECT * FROM SYSTEM.PAYMENT;
SELECT * FROM SYSTEM.PLAN;
