--- SYSTEM
CREATE TABLE INVENTORY.ITEM (
    "id" number DEFAULT ON  NULL to_number(sys_guid(),'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') NOT NULL,
    "name" varchar2(256)   NOT NULL,
    "type" varchar2(256)   NOT NULL,
    "count" number(3)   NOT NULL,
    "description" varchar2(256)   NOT NULL,
    CONSTRAINT "pk_INVENTORY_ITEM" PRIMARY KEY (
        "id"
     )
);

CREATE TABLE INVENTORY.VEHICLE (
    "id" number DEFAULT ON  NULL to_number(sys_guid(),'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') NOT NULL,
    "model" varchar2(256)   NOT NULL,
    "type" varchar2(256)   NOT NULL,
    "count" number(3)   NOT NULL,
    "description" varchar2(256)   NOT NULL,
    CONSTRAINT "pk_INVENTORY_VEHICLE" PRIMARY KEY (
        "id"
     )
);

CREATE TABLE INVENTORY.MISSION (
    "id" number DEFAULT ON  NULL to_number(sys_guid(),'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') NOT NULL,
    "name" varchar2(256)   NOT NULL,
    "description" varchar2(256)   NOT NULL,
    CONSTRAINT "pk_MISSION" PRIMARY KEY (
        "id"
     )
);


CREATE TABLE "INVENTORY"."MISSION_ITEMS" (
    "mission_id" number   NOT NULL,
    "item_id" number   NOT NULL,
    "count" number(3)   NOT NULL
);

CREATE TABLE "INVENTORY"."MISSION_VEHICLES" (
    "mission_id" number   NOT NULL,
    "vehicle_id" number   NOT NULL,
    "count" number(3)   NOT NULL
);

DROP TABLE INVENTORY.ITEM;
DROP TABLE INVENTORY.VEHICLE;
DROP TABLE INVENTORY.MISSION;
DROP TABLE INVENTORY.MISSION_ITEMS;
DROP TABLE INVENTORY.MISSION_VEHICLES;

TRUNCATE TABLE INVENTORY.ITEM;
TRUNCATE TABLE INVENTORY.VEHICLE;
TRUNCATE TABLE INVENTORY.MISSION;
TRUNCATE TABLE INVENTORY.MISSION_ITEMS;
TRUNCATE TABLE INVENTORY.MISSION_VEHICLES;
