-- SYSTEM: Grant accesses
GRANT SELECT,INSERT,UPDATE,DELETE ON INVENTORY.VEHICLE TO CHIEF_COMM;
GRANT SELECT,INSERT,UPDATE,DELETE ON INVENTORY.VEHICLE TO COMM_1;
GRANT SELECT,INSERT,UPDATE,DELETE ON INVENTORY.VEHICLE TO COMM_4;

GRANT SELECT,INSERT,UPDATE,DELETE ON INVENTORY.ITEM TO CHIEF_COMM;
GRANT SELECT,INSERT,UPDATE,DELETE ON INVENTORY.ITEM TO COMM_1;
GRANT SELECT,INSERT,UPDATE,DELETE ON INVENTORY.ITEM TO COMM_4;

GRANT SELECT,INSERT,UPDATE,DELETE ON INVENTORY.MISSION TO CHIEF_COMM;
GRANT SELECT,INSERT,UPDATE,DELETE ON INVENTORY.MISSION TO COMM_1;
GRANT SELECT,INSERT,UPDATE,DELETE ON INVENTORY.MISSION TO COMM_4;

GRANT SELECT,INSERT,UPDATE,DELETE ON INVENTORY.MISSION_ITEMS TO CHIEF_COMM;
GRANT SELECT,INSERT,UPDATE,DELETE ON INVENTORY.MISSION_ITEMS TO COMM_1;
GRANT SELECT,INSERT,UPDATE,DELETE ON INVENTORY.MISSION_ITEMS TO COMM_4;

GRANT SELECT,INSERT,UPDATE,DELETE ON INVENTORY.MISSION_VEHICLES TO CHIEF_COMM;
GRANT SELECT,INSERT,UPDATE,DELETE ON INVENTORY.MISSION_VEHICLES TO COMM_1;
GRANT SELECT,INSERT,UPDATE,DELETE ON INVENTORY.MISSION_VEHICLES TO COMM_4;
