-- Check in env var are initialized
SELECT SYS_CONTEXT('agent_ctx', 'agent_id') agentid FROM DUAL;

EXEC DBMS_SESSION.SET_IDENTIFIER('agent');

SELECT SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER') AS END_USER FROM DUAL;

-- Can only see his/her own customers

SELECT * FROM SYSTEM.CUSTOMER;

-- Can only see payment methods of his/her own customers

SELECT * FROM SYSTEM.PAYMENT;
SELECT * FROM SYSTEM.CUSTOMER INNER JOIN SYSTEM.PAYMENT ON SYSTEM.CUSTOMER.PAYMENT_METHOD_ID = SYSTEM.PAYMENT.PAYMENT_ID;