-- Check in env var are initialized
SELECT SYS_CONTEXT('agent_ctx', 'agent_id') agentid FROM DUAL;

EXEC DBMS_SESSION.SET_IDENTIFIER('agent');

SELECT SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER') AS END_USER FROM DUAL;

-- Can only see his/her own customers

SELECT * FROM SYSTEM.CUSTOMER;

-- Can only see payment methods of his/her own customers

SELECT * FROM SYSTEM.PAYMENT;
SELECT * FROM SYSTEM.CUSTOMER INNER JOIN SYSTEM.PAYMENT ON SYSTEM.CUSTOMER.PAYMENT_METHOD_ID = SYSTEM.PAYMENT.PAYMENT_ID;

-- agent_id value is deliberately omitted and will be automatically populated with SYS_CONTEXT('agent_ctx', 'agent_id')
INSERT INTO SYSTEM.CUSTOMER (CUSTOMER_ID, USERNAME, PASSWORD, CUSTOMER_NAME, CUSTOMER_NRIC, DATE_OF_BIRTH, DATE_JOINED, ADDRESS, MONTHLY_SALARY, MONTHLY_EXPENSES, MOBILE_NUMBER, EMAIL_ADDRESS, PAYMENT_METHOD_ID)  VALUES ('7', 'Test user', 'o7ytw2Zc&%', 'Test user', 'S2345678H', TO_DATE('07-12-1990 00:00:00', 'DD-MM-YYYY HH24:MI:SS'), TO_DATE('02-10-2022 00:00:00', 'DD-MM-YYYY HH24:MI:SS'), '9665 Sheryl Crest\nHarrisonview, SD 65795', '3000', '300', '91234568', 'testuser@example.com', '1');