-- Can add premiums
INSERT INTO SYSTEM.PREMIUM (PREMIUM_ID, CUSTOMER_ID, PAYMENT_DATE, PAYMENT_VALUE_SGD, BANK_TRANSACTION_ID) VALUES ('7', '6', TO_DATE('6/10/2022', 'DD-MM-YYYY HH24:MI:SS'), '20000', 'e2d55eb0-8a45-42a7-8469-04e9c6b5b416');

-- Can view all purchases
SELECT * FROM SYSTEM.PURCHASE WHERE CUSTOMER_ID = 2;

-- Can view all information from customers table except PII
SELECT * FROM SYSTEM.CUSTOMER WHERE CUSTOMER_ID = 2;
